# Generated by Django 4.2 on 2024-01-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='thumbnail',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
