# Generated by Django 4.2 on 2024-01-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_blogarticle_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
