# Generated by Django 4.2 on 2024-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_blogarticle_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='thumbnail',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
