# Generated by Django 4.2 on 2024-02-21 15:17

from django.db import migrations, models
import django_backblaze_b2.storage


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_alter_blogarticle_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='thumbnail',
            field=models.ImageField(storage=django_backblaze_b2.storage.BackblazeB2Storage, upload_to='thumbnail/'),
        ),
    ]
